/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GlassToolBar.java
 *
 * Created on 22-Sep-2010, 15:20:13
 */

package samusik.glasscmp;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.GeneralPath;

/**
 *
 * @author Nikolay
 */
public class GlassToolBar extends javax.swing.JPanel {

    /** Creates new form GlassToolBar */
    public GlassToolBar() {
        initComponents();
    }
    private Color col1 = new Color(245,245,245);
    private Color col2 = new Color(225,225,225);
    private Color col3 = new Color(190,190,190);

    private GradientPaint gp1, gp2, gp3,gp4;
    

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D)g;
        
        GeneralPath left = new GeneralPath();
        
        boolean rot = this.getHeight()> this.getWidth();


        final int hgt = rot?getWidth():getHeight();
        final int wid =  rot?getHeight():getWidth();

        if(rot){
            g2.rotate(-Math.PI/2);
            g2.translate(0, this.getHeight());
        }

        left.moveTo(0,0);
        
        left.lineTo(hgt/9, hgt/7);
        left.lineTo(hgt/9, 6*hgt/7);

        left.lineTo(0,hgt);
        left.closePath();

        GeneralPath right = new GeneralPath();
        

        right.moveTo(wid - (hgt/9),hgt/7);
        right.lineTo(wid, 0);
        right.lineTo(wid,hgt);
        right.lineTo(wid - (hgt/9), 6*hgt/7);
        right.closePath();


        right.lineTo(0,hgt);
        right.closePath();


        g2.setPaint(col1);
        g2.fillRect(0, 0, wid,hgt);
        
        gp1 = new GradientPaint(0,0,col2,0,hgt/7,col1);
        g2.setPaint(gp1);
        g2.fillRect(0, 0,wid, hgt/7);

        gp2 = new GradientPaint(0,6*hgt/7,col1, 0,hgt, col3);
        g2.setPaint(gp2);
        g2.fillRect(0,6*hgt/7,wid, hgt/7);

        gp3 = new GradientPaint(0,0,col2, hgt/8,0,col1);
        g2.setPaint(gp3);
        //g2.setPaint(Color.red);
        g2.fill(left);

        gp4 = new GradientPaint(wid-(hgt/8),0,col1,wid,0,col3);
        g2.setPaint(gp4);
        //g2.setPaint(Color.red);
        g2.fill(right);

        g2.setPaint(col2);
        g2.drawRect(0, 0, wid, hgt-1);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
