/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package samusik.glasscmp;

import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Nikolay
 */
public class WindowDock extends javax.swing.JScrollPane {
    
    private ArrayList<FramePreviewPanel> frames; 
    
    /**
     * Creates new form windowDock
     */
    public WindowDock() {
        initComponents();
        frames = new ArrayList<>();
    }
    
    public void addFrame(JFrame frm){
        FramePreviewPanel pan = new FramePreviewPanel(frm);
        frames.add(pan);
    }
    
    public void removeFrame(JFrame frm){
        for (int i = 0; i < frames.size(); i++) {
            if(frames.get(i).frm == frm){
                frames.remove(i);
                i--;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
